apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delete-task
  template:
    metadata:
      labels:
        app: delete-task
    spec:
      containers:
      - name: delete-task
         env:
           - name: CONNECTION_STRING
             value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todoserverdev.database.windows.net,1433;Database=tododbdev;Uid=sqladminuser;Pwd=P@ssword1234;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: todoazureacr1.azurecr.io/deletetasks:v1
        ports:
        - containerPort: 8000
